package com.cch_lab.java.android.lint.example;

import com.android.annotations.NonNull;
import com.android.tools.lint.checks.infrastructure.LintDetectorTest;
import com.android.tools.lint.client.api.LintClient;
import com.android.tools.lint.detector.api.Issue;
import com.android.tools.lint.detector.api.Project;

import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class PsiClassStructureDetectorTest extends LintDetectorTest {

    /**
     * The set of enabled issues for a given test.
     */
    private Set<Issue> mEnabled = new HashSet<Issue>();

    protected PsiClassStructureDetector getDetector() {
        return new PsiClassStructureDetector();
    }

    @Override
    protected List<Issue> getIssues() {
        return Collections.singletonList(PsiClassStructureDetector.ISSUE);
    }

    /**
     * Gets the configuration for the test.
     * Each test can have a set of enabled issues by assigning the member field {@link #mEnabled}.
     */
    @Override
    protected TestConfiguration getConfiguration(LintClient client, Project project) {
        return new TestConfiguration(client, project, null) {
            @Override
            public boolean isEnabled(@NonNull Issue issue) {
                return super.isEnabled(issue) && mEnabled.contains(issue);
            }
        };
    }

    public void testClassVisit() throws Exception {
        mEnabled = Collections.singleton(PsiClassStructureDetector.ISSUE);
        String expected = "No warnings.";
        String result = lintProject(
                java(
                        "src/test/pkg/MultiLogicFlagTest.java",
                        ""
                                + "package test.pkg;\n"
                                + "\n"
                                + "public class MultiLogicFlagTest {\n"
                                + "\n"
                                + "    private String message;\n"
                                + "    private boolean isSuccess;\n"
                                + "\n"
                                + "    public MultiLogicFlagTest(){\n"
                                + "    }\n"
                                + "\n"
                                + "    public void setup(boolean isSuccess) {\n"
                                + "        // 条件式にメソッドパラメータがある\n"
                                + "        if (isSuccess) {\n"
                                + "            message = \"success step.1\";\n"
                                + "        } else {\n"
                                + "            message = \"failed step.1\";\n"
                                + "        }\n"
                                + "        System.out.println(\"step.1 message -> \" + message);\n"
                                + "        \n"
                                + "        // 条件式にメソッドパラメータがある\n"
                                + "        if (isSuccess) \n"
                                + "            message = \"success step.2\";\n"
                                + "        else \n"
                                + "            message = \"failed step.2\";\n"
                                + "        System.out.println(\"step.2 message -> \" + message);\n"
                                + "        \n"
                                + "        // 条件式にメソッドパラメータがない\n"
                                + "        if (this.isSuccess) {\n"
                                + "            message = \"success step.3\";\n"
                                + "        } else {\n"
                                + "            message = \"failed step.3\";\n"
                                + "        }\n"
                                + "        System.out.println(\"step.3 message -> \" + message);\n"
                                + "        \n"
                                + "        // 条件式にメソッドパラメータがない\n"
                                + "        if (SubClass.isSuccess) {\n"
                                + "            message = \"success step.4\";\n"
                                + "        } else {\n"
                                + "            message = \"failed step.4\";\n"
                                + "        }\n"
                                + "        System.out.println(\"step.4 message -> \" + message);\n"
                                + "        \n"
                                + "        {\n"
                                + "            // フィールド変数を変更していない\n"
                                + "            String message;\n"
                                + "            if (isSuccess) {\n"
                                + "                message = \"success step.5\";\n"
                                + "            } else {\n"
                                + "                message = \"failed step.5\";\n"
                                + "            }\n"
                                + "            System.out.println(\"step.5 message -> \" + message);\n"
                                + "        }\n"
                                + "        \n"
                                + "    }\n"
                                + "\n"
                                + "    static class SubClass {\n"
                                + "\n"
                                + "        private static boolean isSuccess;\n"
                                + "        public SubClass(){\n"
                                + "        }\n"
                                + "\n"
                                + "    }\n"
                                + "\n"
                                + "}"
                ),
                java(
                        "src/test/pkg/MixedMethodsGreet.java",
                        ""
                                + "package test.pkg;\n"
                                + "\n"
                                + "\n"
                                + "import java.util.TimeZone;\n"
                                + "\n"
                                + "public class MixedMethodsGreet {\n"
                                + "\n"
                                + "    private String mGreetName;\n"
                                + "    private String mGreetMessage;\n"
                                + "    private long mGreetTime;\n"
                                + "    private int mGreetCount;\n"
                                + "\n"
                                + "    public MixedMethodsGreet(String name) {\n"
                                + "        init(name);\n"
                                + "    }\n"
                                + "\n"
                                + "    // 状態変更混在メソッド\n"
                                + "    private void init(String name) {\n"
                                + "        mGreetName = name;\n"
                                + "        mGreetMessage = \"\";\n"
                                + "        mGreetTime = 0L;\n"
                                + "        mGreetCount = 0;\n"
                                + "    }\n"
                                + "\n"
                                + "    // 状態変更混在メソッド\n"
                                + "    private void createGreet() {\n"
                                + "        mGreetTime = System.currentTimeMillis();\n"
                                + "        long dayOffset = getDayOffset(mGreetTime);\n"
                                + "        if (dayOffset >= 0 && dayOffset < (3600000*6)) {\n"
                                + "            mGreetMessage = \"ZZZ...\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*6) && dayOffset < (3600000*10)) {\n"
                                + "            mGreetMessage = \"おはようございます。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*10) && dayOffset < (3600000*18)) {\n"
                                + "            mGreetMessage = \"こんにちは。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*18) && dayOffset < (3600000*21)) {\n"
                                + "            mGreetMessage = \"こんばんは。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*21) && dayOffset < (3600000*24)) {\n"
                                + "            mGreetMessage = \"おやすみなさい。\";\n"
                                + "        }\n"
                                + "    }\n"
                                + "\n"
                                + "    // 状態変更混在メソッド\n"
                                + "    public void greet() {\n"
                                + "        mGreetCount = mGreetCount + 1;\n"
                                + "        createGreet();\n"
                                + "        System.out.println(mGreetName+\"さん、\"+mGreetMessage+\" (\"+mGreetCount+\"回目の挨拶)\");\n"
                                + "    }\n"
                                + "\n"
                                + "    // 関数\n"
                                + "    private static long getDayOffset(final long timeInMillis) {\n"
                                + "        long fixedTimestamp = timeInMillis + TIMEZONE_OFFSET_MILLISECOND;\n"
                                + "        long timestampOf12am = (fixedTimestamp / MILLISECOND_AT_A_DAY) * MILLISECOND_AT_A_DAY;\n"
                                + "        return fixedTimestamp - timestampOf12am;\n"
                                + "    }\n"
                                + "    private static final long MILLISECOND_AT_A_DAY = 24 * 3600 * 1000;\n"
                                + "    private static final int TIMEZONE_OFFSET_MILLISECOND = TimeZone.getDefault().getRawOffset();\n"
                                + "}\n"
                ),
                java(
                        "src/test/pkg/ShareAndSingleMethodsGreet.java",
                        ""
                                + "package test.pkg;\n"
                                + "\n"
                                + "import java.util.TimeZone;\n"
                                + "\n"
                                + "public class ShareAndSingleMethodsGreet {\n"
                                + "\n"
                                + "    private String mGreetName;\n"
                                + "    private String mGreetMessage;\n"
                                + "    private long mGreetTime;\n"
                                + "    private int mGreetCount;\n"
                                + "\n"
                                + "    public ShareAndSingleMethodsGreet(String name) {\n"
                                + "        init(name);\n"
                                + "        initGreetTimeCountMessage();\n"
                                + "    }\n"
                                + "\n"
                                + "    // 状態変更独立メソッド\n"
                                + "    private void init(String name) {\n"
                                + "        mGreetName = name;\n"
                                + "    }\n"
                                + "\n"
                                + "    // 状態変更共有メソッド（非唯一）\n"
                                + "    private void initGreetTimeCountMessage() {\n"
                                + "        mGreetMessage = \"\";\n"
                                + "        mGreetTime = 0L;\n"
                                + "        mGreetCount = 0;\n"
                                + "    }\n"
                                + "\n"
                                + "    // 状態変更共有メソッド（非唯一）\n"
                                + "    private void createGreetTimeCountMessage() {\n"
                                + "        mGreetTime = System.currentTimeMillis();\n"
                                + "        long dayOffset = getDayOffset(mGreetTime);\n"
                                + "        if (dayOffset >= 0 && dayOffset < (3600000*6)) {\n"
                                + "            mGreetMessage = \"ZZZ...\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*6) && dayOffset < (3600000*10)) {\n"
                                + "            mGreetMessage = \"おはようございます。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*10) && dayOffset < (3600000*18)) {\n"
                                + "            mGreetMessage = \"こんにちは。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*18) && dayOffset < (3600000*21)) {\n"
                                + "            mGreetMessage = \"こんばんは。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*21) && dayOffset < (3600000*24)) {\n"
                                + "            mGreetMessage = \"おやすみなさい。\";\n"
                                + "        }\n"
                                + "        mGreetCount = mGreetCount + 1;\n"
                                + "    }\n"
                                + "\n"
                                + "    // 関数\n"
                                + "    public void greet() {\n"
                                + "        createGreetTimeCountMessage();\n"
                                + "        System.out.println(mGreetName+\"さん、\"+mGreetMessage+\" (\"+mGreetCount+\"回目の挨拶)\");\n"
                                + "    }\n"
                                + "\n"
                                + "    // 関数\n"
                                + "    private static long getDayOffset(final long timeInMillis) {\n"
                                + "        long fixedTimestamp = timeInMillis + TIMEZONE_OFFSET_MILLISECOND;\n"
                                + "        long timestampOf12am = (fixedTimestamp / MILLISECOND_AT_A_DAY) * MILLISECOND_AT_A_DAY;\n"
                                + "        return fixedTimestamp - timestampOf12am;\n"
                                + "    }\n"
                                + "    private static final long MILLISECOND_AT_A_DAY = 24 * 3600 * 1000;\n"
                                + "    private static final int TIMEZONE_OFFSET_MILLISECOND = TimeZone.getDefault().getRawOffset();\n"
                                + "}\n"
                ),
                java(
                        "src/test/pkg/OnlyShareMethodsGreet.java",
                        ""
                                + "package test.pkg;\n"
                                + "\n"
                                + "import java.util.TimeZone;\n"
                                + "\n"
                                + "public class OnlyShareMethodsGreet {\n"
                                + "\n"
                                + "    private String mGreetName;\n"
                                + "    private String mGreetMessage;\n"
                                + "    private long mGreetTime;\n"
                                + "    private int mGreetCount;\n"
                                + "\n"
                                + "    public OnlyShareMethodsGreet(String name) {\n"
                                + "        mGreetName = name;\n"
                                + "        initGreetTimeCountMessage();\n"
                                + "    }\n"
                                + "\n"
                                + "    // 状態変更共有メソッド（唯一）\n"
                                + "    private void initGreetTimeCountMessage() {\n"
                                + "        mGreetMessage = \"\";\n"
                                + "        mGreetTime = 0L;\n"
                                + "        mGreetCount = 0;\n"
                                + "    }\n"
                                + "\n"
                                + "    // 状態変更共有メソッド（唯一）\n"
                                + "    private void createGreetTimeCountMessage() {\n"
                                + "        mGreetTime = System.currentTimeMillis();\n"
                                + "        long dayOffset = getDayOffset(mGreetTime);\n"
                                + "        if (dayOffset >= 0 && dayOffset < (3600000*6)) {\n"
                                + "            mGreetMessage = \"ZZZ...\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*6) && dayOffset < (3600000*10)) {\n"
                                + "            mGreetMessage = \"おはようございます。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*10) && dayOffset < (3600000*18)) {\n"
                                + "            mGreetMessage = \"こんにちは。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*18) && dayOffset < (3600000*21)) {\n"
                                + "            mGreetMessage = \"こんばんは。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*21) && dayOffset < (3600000*24)) {\n"
                                + "            mGreetMessage = \"おやすみなさい。\";\n"
                                + "        }\n"
                                + "        mGreetCount = mGreetCount + 1;\n"
                                + "    }\n"
                                + "\n"
                                + "    // 関数\n"
                                + "    public void greet() {\n"
                                + "        createGreetTimeCountMessage();\n"
                                + "        System.out.println(mGreetName+\"さん、\"+mGreetMessage+\" (\"+mGreetCount+\"回目の挨拶)\");\n"
                                + "    }\n"
                                + "\n"
                                + "    // 関数\n"
                                + "    private static long getDayOffset(final long timeInMillis) {\n"
                                + "        long fixedTimestamp = timeInMillis + TIMEZONE_OFFSET_MILLISECOND;\n"
                                + "        long timestampOf12am = (fixedTimestamp / MILLISECOND_AT_A_DAY) * MILLISECOND_AT_A_DAY;\n"
                                + "        return fixedTimestamp - timestampOf12am;\n"
                                + "    }\n"
                                + "    private static final long MILLISECOND_AT_A_DAY = 24 * 3600 * 1000;\n"
                                + "    private static final int TIMEZONE_OFFSET_MILLISECOND = TimeZone.getDefault().getRawOffset();\n"
                                + "}\n"
                ),
                java(
                        "src/test/pkg/SrpMethodsGreet.java",
                        ""
                                + "package test.pkg;\n"
                                + "\n"
                                + "import java.util.TimeZone;\n"
                                + "\n"
                                + "public class SrpMethodsGreet {\n"
                                + "\n"
                                + "    private String mGreetName;\n"
                                + "    private String mGreetMessage;\n"
                                + "    private long mGreetTime;\n"
                                + "    private int mGreetCount;\n"
                                + "\n"
                                + "    public SrpMethodsGreet(String name) {\n"
                                + "        mGreetName = name;\n"
                                + "    }\n"
                                + "\n"
                                + "    // 状態変更メソッド （唯一）\n"
                                + "    private void createGreetTimeCountMessage() {\n"
                                + "        mGreetTime = System.currentTimeMillis();\n"
                                + "        long dayOffset = getDayOffset(mGreetTime);\n"
                                + "        if (dayOffset >= 0 && dayOffset < (3600000*6)) {\n"
                                + "            mGreetMessage = \"ZZZ...\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*6) && dayOffset < (3600000*10)) {\n"
                                + "            mGreetMessage = \"おはようございます。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*10) && dayOffset < (3600000*18)) {\n"
                                + "            mGreetMessage = \"こんにちは。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*18) && dayOffset < (3600000*21)) {\n"
                                + "            mGreetMessage = \"こんばんは。\";\n"
                                + "        } else\n"
                                + "        if (dayOffset >= (3600000*21) && dayOffset < (3600000*24)) {\n"
                                + "            mGreetMessage = \"おやすみなさい。\";\n"
                                + "        }\n"
                                + "        mGreetCount = mGreetCount + 1;\n"
                                + "    }\n"
                                + "\n"
                                + "    // 関数\n"
                                + "    public void greet() {\n"
                                + "        createGreetTimeCountMessage();\n"
                                + "        System.out.println(mGreetName+\"さん、\"+mGreetMessage+\" (\"+mGreetCount+\"回目の挨拶)\");\n"
                                + "    }\n"
                                + "\n"
                                + "    // 関数\n"
                                + "    private static long getDayOffset(final long timeInMillis) {\n"
                                + "        long fixedTimestamp = timeInMillis + TIMEZONE_OFFSET_MILLISECOND;\n"
                                + "        long timestampOf12am = (fixedTimestamp / MILLISECOND_AT_A_DAY) * MILLISECOND_AT_A_DAY;\n"
                                + "        return fixedTimestamp - timestampOf12am;\n"
                                + "    }\n"
                                + "    private static final long MILLISECOND_AT_A_DAY = 24 * 3600 * 1000;\n"
                                + "    private static final int TIMEZONE_OFFSET_MILLISECOND = TimeZone.getDefault().getRawOffset();\n"
                                + "}\n"
                )
        );

        assertEquals(expected, result);
    }
}
